version: '2'
services:
  apache:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - "./website:/usr/share/nginx/html"

  mysql:
    image: mysql
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: password1

  wordpress:
    image: wordpress
    ports:
      - 1000:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: password1
    depends_on:
      - mysql

  ruby:
    image: ruby:2.3.1
